// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Search() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"relative\"><div class=\"flex gap-3\"><div class=\"flex-1 relative\"><span class=\"absolute left-4 top-1/2 -translate-y-1/2 text-2xl\">🔍</span> <input type=\"search\" id=\"search-input\" name=\"q\" placeholder=\"Search for music, videos, playlists...\" hx-get=\"/ui/search\" hx-trigger=\"keyup changed delay:300ms, search\" hx-target=\"#results\" hx-indicator=\"#loading\" class=\"neo-input pl-14 text-lg font-medium\"></div></div><div id=\"loading\" class=\"htmx-indicator mt-4\"><div class=\"neo-card p-4 text-center\"><div class=\"inline-flex items-center gap-2\"><div class=\"w-4 h-4 bg-neo-yellow border-2 border-neo-border animate-bounce\"></div><div class=\"w-4 h-4 bg-neo-blue border-2 border-neo-border animate-bounce\" style=\"animation-delay: 0.1s\"></div><div class=\"w-4 h-4 bg-neo-red border-2 border-neo-border animate-bounce\" style=\"animation-delay: 0.2s\"></div></div><p class=\"mt-2 font-semibold\">Searching...</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
